version: "3"

services:
  app:
      build: .
      command: >
        bash -c "npm run debug"
      depends_on:
        - db
      env_file:
        - .env
      volumes:
      - ./app/src:/app/src
  db:
    image: postgres
    restart: always
    container_name: sql1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discordbot
    ports:
      - "5432:5432"