version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - ./app/src:/app/src
    ports:
      - "8000:8000"
    command: >
      bash -c "npm run start"
    network_mode: musicbot
